elecciones/urls.py
from django.conf.urls import url, include
from elecciones.views import ListaCircunscripciones, NuevaCircunscripcion, EditarCircunscripcion, EliminarCircunscripcion, EditarResultados
from . import views

urlpatterns = [
	url(r'circunscripciones/$', ListaCircunscripciones.as_view(), name = 'listacircunscripciones'),
	url(r'circunscripciones/nueva/$', NuevaCircunscripcion.as_view(), name = 'nuevacircunscripcion'),
	url(r'circunscripciones/editar/(?P<id>[0-9]+)/$', EditarCircunscripcion.as_view(), name = 'editarcircunscripcion'),
	url(r'circunscripciones/eliminar/$', EliminarCircunscripcion.as_view(), name = 'eliminarcircunscripcion'),
	url(r'mesas/(?P<idcir>[0-9]+)/$', views.lista_mesas, name='listamesas'),
	url(r'mesas/nueva/(?P<idcir>[0-9]+)/$', views.nueva_mesa, name = 'nuevamesa'),
	url(r'mesas/editar/(?P<id>[0-9]+)/$', views.editar_mesa, name = 'editarmesa'),
	url(r'mesas/detalle/(?P<id>[0-9]+)/$', views.detalles_mesa, name = 'detallesmesa'),
	url(r'mesas/eliminar/$', views.eliminar_mesa, name = 'eliminarmesa'),
	url(r'resultados/(?P<mid>[0-9]+)/$', EditarResultados.as_view(), name = 'editarresultados'),
	url(r'registration/', include('django.contrib.auth.urls')),
	url('^$',views.index, name= 'index'),


]

examen/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('elecciones.urls', namespace='elecciones')),

]

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Elecciones{% endblock %}</title>
</head>
<body>

<div class="container">
<ul>
	<li><a href="{%url 'elecciones:listacircunscripciones'%}">Lista de circunscripciones</a></li>

	{%if user.is_anonymous%}

	<li><a href="{%url 'elecciones:login'%}">Login</a></li>

	{%else%}

	<li>Bienvenido {{user.username}}</li>

	<li><a href="{%url 'elecciones:logout'%}?next=/">Logout</a></li>

	{%endif%}
</ul>
	{% block content %}{% endblock content %}
</div>
</body>
</html>