elecciones/urls.py
from django.conf.urls import url, include
from elecciones.views import ListaCircunscripciones, NuevaCircunscripcion, EditarCircunscripcion, EliminarCircunscripcion, EditarResultados
from . import views

urlpatterns = [
	url(r'circunscripciones/$', ListaCircunscripciones.as_view(), name = 'listacircunscripciones'),
	url(r'circunscripciones/nueva/$', NuevaCircunscripcion.as_view(), name = 'nuevacircunscripcion'),
	url(r'circunscripciones/editar/(?P<id>[0-9]+)/$', EditarCircunscripcion.as_view(), name = 'editarcircunscripcion'),
	url(r'circunscripciones/eliminar/$', EliminarCircunscripcion.as_view(), name = 'eliminarcircunscripcion'),
	url(r'mesas/(?P<idcir>[0-9]+)/$', views.lista_mesas, name='listamesas'),
	url(r'mesas/nueva/(?P<idcir>[0-9]+)/$', views.nueva_mesa, name = 'nuevamesa'),
	url(r'mesas/editar/(?P<id>[0-9]+)/$', views.editar_mesa, name = 'editarmesa'),
	url(r'mesas/detalle/(?P<id>[0-9]+)/$', views.detalles_mesa, name = 'detallesmesa'),
	url(r'mesas/eliminar/$', views.eliminar_mesa, name = 'eliminarmesa'),
	url(r'resultados/(?P<mid>[0-9]+)/$', EditarResultados.as_view(), name = 'editarresultados'),
	url(r'registration/', include('django.contrib.auth.urls')),
	url('^$',views.index, name= 'index'),


]

examen/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('elecciones.urls', namespace='elecciones')),

]

elecciones/models.py
from __future__ import unicode_literals

from django.db import models

#from django.contrib.auth.models import User

# Create your models here.
class Circunscripcion(models.Model):
	nombre = models.CharField(max_length=100)
	num_esc = models.IntegerField()

	def __str__(self):
		return self.nombre


class Mesa(models.Model):
	nombre = models.CharField(max_length=100)
	circunscripcion = models.ForeignKey(Circunscripcion, on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre


class Partido(models.Model):
	nombre = models.CharField(max_length=100, unique=True)

	def __str__(self):
		return self.nombre

class Resultado(models.Model):
	votos = models.IntegerField(default = 0)
	partido = models.ForeignKey(Partido, on_delete=models.CASCADE)
	mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE)

	def __str__(self):
		return self.mesa.nombre + " - " + self.partido.nombre

elecciones/forms.py
from django.forms import ModelForm
from elecciones.models import Circunscripcion, Mesa, Resultado

class CircunscripcionForm(ModelForm):
	class Meta:
		model = Circunscripcion
		exclude = ()

class MesaForm(ModelForm):
	class Meta:
		model = Mesa
		exclude = ()

class ResultadosForm(ModelForm):
	class Meta:
		model = Resultado
		exclude = ('mesa',)

elecciones/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.views import redirect_to_login
from django.views import View
from elecciones.models import Circunscripcion, Mesa, Partido, Resultado
from elecciones.forms import CircunscripcionForm, MesaForm, ResultadosForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum

# Create your views here.

class ListaCircunscripciones(View):
	template_name = 'elecciones/lista_circunscripciones.html'

	def get(self, request, *args, **kwargs):
		circunscripciones = Circunscripcion.objects.all()
		return render(request, self.template_name, { 'circunscripciones' : circunscripciones })




class NuevaCircunscripcion(View):
	template_name = 'elecciones/editar_circunscripcion.html'
	form_class = CircunscripcionForm

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('elecciones:listacircunscripciones'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(NuevaCircunscripcion, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('elecciones:nuevacircunscripcion'))





class EditarCircunscripcion(View):
	template_name = 'elecciones/editar_circunscripcion.html'
	form_class = CircunscripcionForm

	def get(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Circunscripcion, pk = c_id)
		if not c:
			return redirect(reverse('elecciones:listacircunscripciones'))

		form = self.form_class(instance = c)
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Circunscripcion, pk = c_id)
		if not c:
			return redirect(reverse('elecciones:listacircunscripciones'))
		form = self.form_class(request.POST, instance = c)

		if form.is_valid():
			form.save()
			return redirect(reverse('elecciones:listacircunscripciones'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EditarCircunscripcion, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('elecciones:editarcircunscripcion', kwargs = { 'id' : kwargs['id'] }))




class EliminarCircunscripcion(View):

	def get(self, request, *args, **kwargs):
		return redirect(reverse('elecciones:listacircunscripciones'))

	def post(self, request, *args, **kwargs):
		c_id = request.POST.get('id')
		c = get_object_or_404(Circunscripcion, pk = c_id)
		c.delete()
		return redirect(reverse('elecciones:listacircunscripciones'))

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EliminarCircunscripcion, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('elecciones:listacircunscripciones'))







def lista_mesas(request, idcir):
	template_name = 'elecciones/lista_mesas.html'

	if request.method == 'GET':
		cir = get_object_or_404(Circunscripcion, pk = idcir)
		if not cir:
			return redirect_to_login(reverse('elecciones:listacircunscripciones'))
		mesas = cir.mesa_set.all()
		resultados = Resultado.objects.filter(mesa__circunscripcion = cir).values('partido').annotate(recuento = Sum('votos')).order_by('-recuento')
		
		for r in resultados:
			r['partido'] = get_object_or_404(Partido, pk = r['partido'])
			r['esc'] = 0

		if resultados.count() == 1:
			resultados[0]['esc'] = cir.num_esc

		if resultados.count() > 1:
			resultados[0]['esc'] = cir.num_esc - 1
			resultados[1]['esc'] = 1

		return render(request, template_name, { 'mesas' : mesas, 'idcir' : idcir, 'resultados' : resultados })

def detalles_mesa(request, id):
	template_name = 'elecciones/detalles_mesa.html'

	if request.method == 'GET':
		mesa = get_object_or_404(Mesa, pk = id)
		resultados = mesa.resultado_set.order_by('-votos').all()

		if not mesa:
			return redirect_to_login(reverse('elecciones:listacircunscripciones'))
		return render(request, template_name, { 'mesa' : mesa, 'resultados' : resultados })


def nueva_mesa(request, idcir):
	template_name = 'elecciones/editar_mesa.html'
	form_class = MesaForm

	if not request.user.is_staff:
		return redirect_to_login(reverse('elecciones:nuevamesa', kwargs = { 'idcir' : idcir }))

	cir = get_object_or_404(Circunscripcion, pk = idcir)

	if request.method == 'POST':
		form = form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('elecciones:listamesas', kwargs = {'idcir' : form.cleaned_data['circunscripcion'].id }))
	else:
		form = form_class(initial = { 'circunscripcion' : cir })
	return render(request, template_name, { 'form' : form })

def editar_mesa(request, id):
	template_name = 'elecciones/editar_mesa.html'
	form_class = MesaForm

	if not request.user.is_staff:
		return redirect_to_login(reverse('elecciones:editarmesa', kwargs = { 'id' : id }))

	mesa = get_object_or_404(Mesa, pk = id)
	if not mesa:
		return redirect(reverse('elecciones:listacircunscripciones'))

	if request.method == 'POST':
		form = form_class(request.POST, instance = mesa)

		if form.is_valid():
			form.save()
			return redirect(reverse('elecciones:listamesas', kwargs = {'idcir' : form.cleaned_data['circunscripcion'].id }))
	else:
		form = form_class(instance = mesa)
	return render(request, template_name, { 'form' : form })

def eliminar_mesa(request):
	idmesa = request.POST.get('id')
	mesa = get_object_or_404(Mesa, pk = idmesa)
	idcir = mesa.circunscripcion.id

	if not request.user.is_staff:
		return redirect_to_login(reverse('elecciones:listamesas', kwargs = { 'idcir' : idcir }))

	if request.method == 'POST':
		mesa.delete()
		
	return redirect(reverse('elecciones:listamesas', kwargs = { 'idcir' : idcir }))







class EditarResultados(LoginRequiredMixin, View):
	template_name = 'elecciones/editar_resultados.html'
	form_class = ResultadosForm

	def get(self, request, *args, **kwargs):
		m_id = kwargs['mid']
		m = get_object_or_404(Mesa, pk = m_id)
		form = self.form_class(initial = { 'mesa' : m })
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		m_id = kwargs['mid']
		p_id = request.POST.get('partido')
		m = get_object_or_404(Mesa, pk = m_id)
		p = get_object_or_404(Partido, pk = p_id)
		r,creado = Resultado.objects.get_or_create(partido = p, mesa = m)
		form = self.form_class(request.POST, instance = r)

		if form.is_valid():
			form.save()
			return redirect(reverse('elecciones:detallesmesa', kwargs = { 'id' : m_id }))
		return render(request, self.template_name, { 'form' : form })




def index(request):
	template_name = 'elecciones/index.html'
	
	return render(request, template_name)

elecciones/templates/elecciones/detalles_mesa.html
{% extends "base.html" %}

{% block title %}Detalles de la mesa electoral{% endblock title %}

{% block content %}
<h3>Detalles de la mesa electoral</h3>
<p>Nombre: {{ mesa.nombre }}</p>
<p>Circunscripción: {{ mesa.circunscripcion.nombre }}</p>

{% if resultados %}
	<table>
		<thead>
			<tr>
				<th>Partido</th>
				<th>Votos</th>
			</tr>
		</thead>
		<tbody>
		{% for r in resultados %}
			<tr>
				<td>{{ r.partido.nombre }}</td>
				<td>{{ r.votos }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}

{% if request.user %}
	<small><a href="{% url 'elecciones:editarresultados' mesa.id %}">Editar resultados</a></small>
{% endif %}
{% endblock content %}

elecciones/templates/elecciones/editar_circunscripcion.html
{% extends "base.html" %}

{% block title %}Editar circunscripcion{% endblock title %}

{% block content %}
<h3>Editar circunscripción</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

elecciones/templates/elecciones/editar_mesa.html
{% extends "base.html" %}

{% block title %}Editar mesa electoral{% endblock title %}

{% block content %}
<h3>Editar mesa electoral</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

elecciones/templates/elecciones/editar_resultados.html
{% extends "base.html" %}

{% block title %}Editar resultados de la mesa electoral{% endblock title %}

{% block content %}
<h3>Editar resultados de la mesa electoral</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

elecciones/templates/elecciones/index.html
{%extends 'base.html'%}
{%block title %}Pagina principal{%endblock%}

{%block content %}<h3>Bienvenido</h3>{%endblock%}

elecciones/templates/elecciones/lista_circunscripciones.html
{% extends "base.html" %}

{% block title %}Circunscripciones{% endblock title %}

{% block content %}
<h3>Listado de circunscripciones</h3>
{% if circunscripciones %}
	<ul>
	{% for c in circunscripciones %}
		<li><a href="{% url 'elecciones:listamesas' c.id %}">{{ c.nombre }}</a> ({{ c.num_esc }} escaños) 
		{% if request.user.is_staff %}
		<small><a href="{% url 'elecciones:editarcircunscripcion' c.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'elecciones:eliminarcircunscripcion' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ c.id }}" name="id">
			<button onclick="return confirm('Desea eliminar esta circunscripción?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ninguna circunscripción.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'elecciones:nuevacircunscripcion' %}">Añadir circunscripción</a></small>
{% endif %}
{% endblock content %}

elecciones/templates/elecciones/lista_mesas.html
{% extends "base.html" %}

{% block title %}Mesas electorales{% endblock title %}

{% block content %}
<h3>Listado de mesas electorales</h3>
{% if mesas %}
	<ul>
	{% for m in mesas %}
		<li><a href="{% url 'elecciones:detallesmesa' m.id %}">{{ m.nombre }}</a> 
		{% if request.user.is_staff %}
		<small><a href="{% url 'elecciones:editarmesa' m.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'elecciones:eliminarmesa' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ m.id }}" name="id">
			<button onclick="return confirm('Desea eliminar esta mesa electoral?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ninguna mesa electoral.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'elecciones:nuevamesa' idcir %}">Añadir nueva mesa</a></small>
{% endif %}
<hr>
<h3> Resultados de la circunscripción</h3>
{% if resultados %}
	<table>
		<thead>
			<tr>
				<th>Partido</th>
				<th>Votos</th>
				<th>Escaños</th>
			</tr>
		</thead>
		<tbody>
		{% for r in resultados %}
			<tr>
				<td>{{ r.partido.nombre }}</td>
				<td>{{ r.recuento }}</td>
				<td>{{ r.esc }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}
{% endblock content %}